uppercase = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
                 'U', 'V', 'W', 'X', 'Y', 'Z']
lowercase = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
                 'u', 'v', 'w', 'x', 'y', 'z']
encode=[]
str=input("Enter the string")
str=str.casefold()
a=str.replace('a','d')
b=str.replace('b','e')
c=str.replace('c','f')
d=str.replace('d','g')
e=str.replace('e','h')
f=str.replace('f','i')
g=str.replace('g','j')
h=str.replace('h','k')
i=str.replace('i','l')
j=str.replace('j','m')
k=str.replace('k','n')
l=str.replace('l','o')
m=str.replace('m','p')
n=str.replace('n','q')
o=str.replace('o','r')
p=str.replace('p','s')
q=str.replace('q','t')
r=str.replace('r','u')
s=str.replace('s','v')
t=str.replace('t','w')
u=str.replace('u','x')
v=str.replace('v','y')
w=str.replace('w','z')
x=str.replace('x','a')
y=str.replace('y','b')
z=str.replace('z','c')
print(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z)
